AllCops:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'lib/kong_schema/cli.rb'

Lint/EndAlignment:
  AlignWith: variable

Style/EachWithObject:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Style/ModuleFunction:
  EnforcedStyle: extend_self